from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(256, 341)
        MainWindow.setMaximumSize(QtCore.QSize(256, 341))
        MainWindow.setMinimumSize(QtCore.QSize(256, 341))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 251, 311))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 110, 208, 170))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.D2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.D2.setText("")
        self.D2.setObjectName("D2")
        self.gridLayout.addWidget(self.D2, 3, 1, 1, 1)
        self.A2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.A2.setText("")
        self.A2.setObjectName("A2")
        self.gridLayout.addWidget(self.A2, 0, 1, 1, 1)
        self.A3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.A3.setText("")
        self.A3.setObjectName("A3")
        self.gridLayout.addWidget(self.A3, 0, 2, 1, 1)
        self.B2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.B2.setText("")
        self.B2.setObjectName("B2")
        self.gridLayout.addWidget(self.B2, 1, 1, 1, 1)
        self.A1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.A1.setText("")
        self.A1.setObjectName("A1")
        self.gridLayout.addWidget(self.A1, 0, 0, 1, 1)
        self.B1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.B1.setText("")
        self.B1.setObjectName("B1")
        self.gridLayout.addWidget(self.B1, 1, 0, 1, 1)
        self.B3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.B3.setText("")
        self.B3.setObjectName("B3")
        self.gridLayout.addWidget(self.B3, 1, 2, 1, 1)
        self.D3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.D3.setText("")
        self.D3.setObjectName("D3")
        self.gridLayout.addWidget(self.D3, 3, 2, 1, 1)
        self.D5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.D5.setText("")
        self.D5.setObjectName("D5")
        self.gridLayout.addWidget(self.D5, 3, 4, 1, 1)
        self.D4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.D4.setText("")
        self.D4.setObjectName("D4")
        self.gridLayout.addWidget(self.D4, 3, 3, 1, 1)
        self.D1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.D1.setText("")
        self.D1.setObjectName("D1")
        self.gridLayout.addWidget(self.D1, 3, 0, 1, 1)
        self.B5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.B5.setText("")
        self.B5.setObjectName("B5")
        self.gridLayout.addWidget(self.B5, 1, 4, 1, 1)
        self.B4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.B4.setText("")
        self.B4.setObjectName("B4")
        self.gridLayout.addWidget(self.B4, 1, 3, 1, 1)
        self.A5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.A5.setText("")
        self.A5.setObjectName("A5")
        self.gridLayout.addWidget(self.A5, 0, 4, 1, 1)
        self.E2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.E2.setText("")
        self.E2.setObjectName("E2")
        self.gridLayout.addWidget(self.E2, 4, 1, 1, 1)
        self.E3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.E3.setText("")
        self.E3.setObjectName("E3")
        self.gridLayout.addWidget(self.E3, 4, 2, 1, 1)
        self.E4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.E4.setText("")
        self.E4.setObjectName("E4")
        self.gridLayout.addWidget(self.E4, 4, 3, 1, 1)
        self.C3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.C3.setText("")
        self.C3.setObjectName("C3")
        self.gridLayout.addWidget(self.C3, 2, 2, 1, 1)
        self.C2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.C2.setText("")
        self.C2.setObjectName("C2")
        self.gridLayout.addWidget(self.C2, 2, 1, 1, 1)
        self.C4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.C4.setText("")
        self.C4.setObjectName("C4")
        self.gridLayout.addWidget(self.C4, 2, 3, 1, 1)
        self.C5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.C5.setText("")
        self.C5.setObjectName("C5")
        self.gridLayout.addWidget(self.C5, 2, 4, 1, 1)
        self.E5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.E5.setText("")
        self.E5.setObjectName("E5")
        self.gridLayout.addWidget(self.E5, 4, 4, 1, 1)
        self.C1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.C1.setText("")
        self.C1.setObjectName("C1")
        self.gridLayout.addWidget(self.C1, 2, 0, 1, 1)
        self.E1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.E1.setText("")
        self.E1.setObjectName("E1")
        self.gridLayout.addWidget(self.E1, 4, 0, 1, 1)
        self.A4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.A4.setText("")
        self.A4.setObjectName("A4")
        self.gridLayout.addWidget(self.A4, 0, 3, 1, 1)
        self.Timer_Label = QtWidgets.QLabel(parent=self.page)
        self.Timer_Label.setGeometry(QtCore.QRect(40, 90, 80, 13))
        self.Timer_Label.setObjectName("Timer_Label")
        self.Flags_Label = QtWidgets.QLabel(parent=self.page)
        self.Flags_Label.setGeometry(QtCore.QRect(140, 90, 47, 13))
        self.Flags_Label.setObjectName("Flags_Label")
        self.Title_Label = QtWidgets.QLabel(parent=self.page)
        self.Title_Label.setGeometry(QtCore.QRect(60, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Title_Label.setFont(font)
        self.Title_Label.setObjectName("Title_Label")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Win_Label = QtWidgets.QLabel(parent=self.page_2)
        self.Win_Label.setGeometry(QtCore.QRect(100, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Win_Label.setFont(font)
        self.Win_Label.setObjectName("Win_Label")
        self.Reset_Button = QtWidgets.QPushButton(parent=self.page_2)
        self.Reset_Button.setGeometry(QtCore.QRect(40, 240, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Reset_Button.setFont(font)
        self.Reset_Button.setObjectName("Reset_Button")
        self.Best_Times_Label = QtWidgets.QLabel(parent=self.page_2)
        self.Best_Times_Label.setGeometry(QtCore.QRect(85, 100, 201, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Best_Times_Label.setFont(font)
        self.Best_Times_Label.setObjectName("Best_Times_Label")
        self.Times_Label = QtWidgets.QLabel(parent=self.page_2)
        self.Times_Label.setGeometry(QtCore.QRect(15, 60, 250, 20))
        self.Times_Label.setObjectName("Times_Label")
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Times_Label.setFont(font)
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 256, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Timer_Label.setText(_translate("MainWindow", "Time: 00:00:00"))
        self.Flags_Label.setText(_translate("MainWindow", "Mines: 3"))
        self.Title_Label.setText(_translate("MainWindow", "Minesweeper"))
        self.Win_Label.setText(_translate("MainWindow", "Win!"))
        self.Reset_Button.setText(_translate("MainWindow", "Reset"))
        self.Best_Times_Label.setText(_translate("MainWindow", "Times"))
        self.Times_Label.setText(_translate("MainWindow", "Your Time:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())