from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(241, 341)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 120, 186, 170))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.D2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.D2.setText("")
        self.D2.setObjectName("D2")
        self.gridLayout.addWidget(self.D2, 3, 1, 1, 1)
        self.A2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.A2.setText("")
        self.A2.setObjectName("A2")
        self.gridLayout.addWidget(self.A2, 0, 1, 1, 1)
        self.A3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.A3.setText("")
        self.A3.setObjectName("A3")
        self.gridLayout.addWidget(self.A3, 0, 2, 1, 1)
        self.B2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.B2.setText("")
        self.B2.setObjectName("B2")
        self.gridLayout.addWidget(self.B2, 1, 1, 1, 1)
        self.A1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.A1.setText("")
        self.A1.setObjectName("A1")
        self.gridLayout.addWidget(self.A1, 0, 0, 1, 1)
        self.B1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.B1.setText("")
        self.B1.setObjectName("B1")
        self.gridLayout.addWidget(self.B1, 1, 0, 1, 1)
        self.B3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.B3.setText("")
        self.B3.setObjectName("B3")
        self.gridLayout.addWidget(self.B3, 1, 2, 1, 1)
        self.D3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.D3.setText("")
        self.D3.setObjectName("D3")
        self.gridLayout.addWidget(self.D3, 3, 2, 1, 1)
        self.D5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.D5.setText("")
        self.D5.setObjectName("D5")
        self.gridLayout.addWidget(self.D5, 3, 4, 1, 1)
        self.D4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.D4.setText("")
        self.D4.setObjectName("D4")
        self.gridLayout.addWidget(self.D4, 3, 3, 1, 1)
        self.D1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.D1.setText("")
        self.D1.setObjectName("D1")
        self.gridLayout.addWidget(self.D1, 3, 0, 1, 1)
        self.B5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.B5.setText("")
        self.B5.setObjectName("B5")
        self.gridLayout.addWidget(self.B5, 1, 4, 1, 1)
        self.B4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.B4.setText("")
        self.B4.setObjectName("B4")
        self.gridLayout.addWidget(self.B4, 1, 3, 1, 1)
        self.A5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.A5.setText("")
        self.A5.setObjectName("A5")
        self.gridLayout.addWidget(self.A5, 0, 4, 1, 1)
        self.E2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.E2.setText("")
        self.E2.setObjectName("E2")
        self.gridLayout.addWidget(self.E2, 4, 1, 1, 1)
        self.E3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.E3.setText("")
        self.E3.setObjectName("E3")
        self.gridLayout.addWidget(self.E3, 4, 2, 1, 1)
        self.E4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.E4.setText("")
        self.E4.setObjectName("E4")
        self.gridLayout.addWidget(self.E4, 4, 3, 1, 1)
        self.C3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.C3.setText("")
        self.C3.setObjectName("C3")
        self.gridLayout.addWidget(self.C3, 2, 2, 1, 1)
        self.C2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.C2.setText("")
        self.C2.setObjectName("C2")
        self.gridLayout.addWidget(self.C2, 2, 1, 1, 1)
        self.C4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.C4.setText("")
        self.C4.setObjectName("C4")
        self.gridLayout.addWidget(self.C4, 2, 3, 1, 1)
        self.C5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.C5.setText("")
        self.C5.setObjectName("C5")
        self.gridLayout.addWidget(self.C5, 2, 4, 1, 1)
        self.E5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.E5.setText("")
        self.E5.setObjectName("E5")
        self.gridLayout.addWidget(self.E5, 4, 4, 1, 1)
        self.C1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.C1.setText("")
        self.C1.setObjectName("C1")
        self.gridLayout.addWidget(self.C1, 2, 0, 1, 1)
        self.E1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.E1.setText("")
        self.E1.setObjectName("E1")
        self.gridLayout.addWidget(self.E1, 4, 0, 1, 1)
        self.A4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.A4.setText("")
        self.A4.setObjectName("A4")
        self.gridLayout.addWidget(self.A4, 0, 3, 1, 1)
        self.Title_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Title_Label.setGeometry(QtCore.QRect(60, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Title_Label.setFont(font)
        self.Title_Label.setObjectName("Title_Label")
        self.Flags_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Flags_Label.setGeometry(QtCore.QRect(150, 100, 47, 13))
        self.Flags_Label.setObjectName("Flags_Label")
        self.Timer_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Timer_Label.setGeometry(QtCore.QRect(50, 100, 47, 13))
        self.Timer_Label.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 241, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title_Label.setText(_translate("MainWindow", "Minesweeper"))
        self.Flags_Label.setText(_translate("MainWindow", "Flags: 3"))
        self.Timer_Label.setText(_translate("MainWindow", "Time: 00"))